### PR TITLE
Netty4 merged with master (plus updates)

### PR DESCRIPTION
**Pull request by JChrist**
I have merged all latest changes within master to netty4 (including AlertNotification and ReplaceSm)
I updated pom to match master (apart from netty 4 dependency)
I updated netty 4 to latest release 4.0.35.Final
Do you think this can come out as a new release in the 6.0.0-netty4 series?

### CODE REVIEW

**Comment by jjlauer** [comment]
Wow, nice merge!  That must have been a ton of work :-)

As a side note, I wish we had forgone a netty4 branch and actually did sub-modules that implemented bindings to netty3, netty4, and even my preferred nio library these days to xnio.  Originally, we thought we could make the jump to netty4 and nix netty3, but folks still use the two different versions.

I'm happy to take a look at this and do a release for you.  Stay tuned.

**Comment by JChrist** [comment]
Thanks!
I would be more than happy to assist with that, so if you have any kind of roadmap or list of tasks that I can go through, please share.

**Comment by jjlauer** [comment]
Pushed your changes out to maven central and updated some of the README.md

**Comment by jjlauer** [comment]
@JChrist I wrote up a summary of the netty3/netty4 idea.  https://github.com/fizzed/cloudhopper-smpp/issues/7

**Pull request merged**
